Some additional entries for Supervised Learning and Statistics sections
Machine-Learning-Tokyo/EN-JP-ML-Lexicon pull request #10
Opened 2020-05-19 12:14 UTC by alexmalins

- Some additional entries for Supervised Learning and Statistics sections
- Also sort the Algebra and Calculus section alphabetically

2020-05-23 14:17 UTC, ytknzw requested changes

2020-05-23 14:17 UTC, ytknzw commented on README.md
> +| Cross validation | クロスバリデーション |
```suggestion
| Cross validation | 交差検証 / クロスバリデーション|
```

2020-05-23 14:17 UTC, ytknzw commented on README.md
> +| Row          | 行目                |
```suggestion
| Row          | 行                |
```

2020-05-23 14:17 UTC, ytknzw commented on README.md
>  | Column          | 列目                   |
```suggestion
| Column          | 列                   |
```

2020-05-23 14:33 UTC, alexmalins commented
Thanks!

2020-06-01 06:32 UTC, suzana-ilic commented
Thank you both for your contributions!

2020-06-01 06:32 UTC, merged